# Generated by Django 4.2 on 2023-04-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='proyect',
            new_name='project',
        ),
    ]
